import {Dimensions, StyleSheet} from 'react-native';
import {DateScreen} from './date.screen';

export const DateScreenStyle = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  componentContainer: {
    left: 16,
    top: 64,
    position: 'relative',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  chooseDateCard: {
    alignSelf: 'center',
    position: 'relative',
    width: 343,
    height: 501,
    top: 71,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    borderRadius: 16,
    boxSizing: 'border-box', // box-sizing is not supported in React Native
  },
  dateInputFrame: {
    position: 'relative',
    width: 295,
    height: 64,
    left: 24,
    top: 40,
    justifyContent: 'center',
    paddingLeft: 12,
    paddingRight: 12,
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EBEBEB',
    borderRadius: 8,
    text: {
      position: 'relative',
      fontFamily: 'Poppins',
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: 14,
      color: '#666666',
    },
  },
  text: {
    position: 'relative',
    width: 157,
    height: 36,
    left: 24,
    top: 24,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 24,
    lineHeight: 36,
    color: '#000000',
  },
  dateDisplayer: {
    position: 'relative',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: 295,
    height: 109,
    top: 180,
    backgroundColor: '#F0F6FF',
    borderRadius: 8,
    // box-sizing is not supported in React Native
  },
  displayedDateText: {
    position: 'relative',
    width: 205,
    height: 46,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 15, // or use lineHeight: '83%'
    textAlign: 'center',
    color: '#1E293A',
  },
  continueFrame: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    position: 'absolute',
    width: Dimensions.get('screen').width,
    height: Dimensions.get('screen').height - 700,
    top: 700,
    backgroundColor: '#FFFFFF',
    buttonContainer: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 22,
      gap: 10,
      position: 'relative',
      width: 123,
      height: 37,
      backgroundColor: '#1E293A',
      borderRadius: 22,
      appButtonTextWhite: {
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 14,
        lineHeight: 21,
        color: '#FFFFFF',
      },
      appButtonTextBlack: {
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 14,
        lineHeight: 21,
        color: '#000000',
      },
    },
  },
  icon: {
    width: 30,
    height: 30,
  },
  dateText: {
    position: 'relative',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    color: '#666666',
  },
  dateText2: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#1E293A',
  },
});
