import {StyleSheet} from 'react-native';

export const terraStyle = StyleSheet.create({
  mainContainer: {
    //padding: 10,
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  terraExclude: {
    position: 'absolute',
    width: 44,
    height: 44,
    left: 166,
    top: 66,
  },
  //text container
  textContainer1: {
    position: 'absolute',
    width: 258,
    height: 72,
    left: 58,
    top: 123,
  },
  text1: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    color: '#000000',
  },
  //description
  rulesContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 32,
    gap: 40,
    position: 'absolute',
    width: 343,
    height: 472.19,
    left: 16,
    top: 227,
    backgroundColor: '#EBEBEB',
    borderRadius: 16,
  },
  innerIconTextContainer: {
    flex: 1,
    flexDirection: 'row',
    // justifyContent: 'space-between',
    alignItems: 'center',
  },
  icon: {
    position: 'absolute',
    width: 30,
    height: 30,
  },
  ruleTitle: {
    width: 245,
    height: 17,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 13,
    lineHeight: 17 * 1.3,
    color: '#000000',
    flex: 0,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  ruleText: {
    width: 245,
    height: 51,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 11,
    lineHeight: 16,
    color: '#000000',
    flex: 0,
    alignSelf: 'stretch',
    flexGrow: 0,
    order: 1,
  },
  //button
  appButtonText: {
    width: 'auto',
    height: 17,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 13,
    color: '#FFFFFF',
    flex: 0, // equivalent to "flex: none"
    flexGrow: 0, // equivalent to "flex-grow: 0"
  },
  button1: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8.09668,
    margin: 8.1,
    width: 169.22,
    height: 33.19,
    backgroundColor: '#1E293A',
    borderRadius: 6.47734,
    flex: 0,
    flexGrow: 0,
    order: 1,
  },
  container: {
    flex: 1,
  },
  text: {
    fontWeight: '500',
    fontSize: 50,
  },
});
